using LIS.Api.Models;
using LIS.Api.Repositories;
using Microsoft.AspNetCore.Mvc;

namespace LIS.Api.Controllers
{
    [ApiController]
    [Route("api/[controller]")]
    public class LabTestsController : ControllerBase
    {
        private readonly ILabTestsRepository _repo;
        private readonly ILogger<LabTestsController> _logger;

        public LabTestsController(ILabTestsRepository repo, ILogger<LabTestsController> logger)
        {
            _repo = repo;
            _logger = logger;
        }

        /// <summary>
        /// Get all lab tests from SQL Server
        /// </summary>
        [HttpGet]
        public async Task<ActionResult<IEnumerable<LabTest>>> GetAll()
        {
            try
            {
                var items = await _repo.GetAllAsync();
                _logger.LogInformation("Retrieved {Count} lab tests from database", items.Count);
                return Ok(items);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error retrieving lab tests from database");
                return StatusCode(500, "An error occurred while retrieving lab tests");
            }
        }

        /// <summary>
        /// Get a specific lab test by ID from SQL Server
        /// </summary>
        [HttpGet("{id:int}")]
        public async Task<ActionResult<LabTest>> GetById(int id)
        {
            try
            {
                var item = await _repo.GetByIdAsync(id);
                if (item == null)
                {
                    _logger.LogWarning("Lab test with ID {Id} not found", id);
                    return NotFound(new { message = $"Lab test with ID {id} not found" });
                }
                return Ok(item);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error retrieving lab test {Id} from database", id);
                return StatusCode(500, "An error occurred while retrieving the lab test");
            }
        }

        /// <summary>
        /// Create a new lab test in SQL Server
        /// </summary>
        [HttpPost]
        public async Task<ActionResult<LabTest>> Create([FromBody] LabTest input)
        {
            try
            {
                // Set default values for required fields
                input.ID = 0; // Will be auto-generated by database
                input.CreatedDate = DateTime.UtcNow;
                input.CreatedBy = input.CreatedBy == 0 ? -1 : input.CreatedBy; // Default to -1 if not specified
                input.Priority = input.Priority == 0 ? 1 : input.Priority;
                input.DisplayOrder = string.IsNullOrEmpty(input.DisplayOrder) ? "0" : input.DisplayOrder;
                input.IsDeleted = false;

                var created = await _repo.CreateAsync(input);
                _logger.LogInformation("Created new lab test with ID {Id}", created.ID);
                
                return CreatedAtAction(nameof(GetById), new { id = created.ID }, created);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error creating lab test in database");
                return StatusCode(500, "An error occurred while creating the lab test");
            }
        }

        /// <summary>
        /// Update an existing lab test in SQL Server
        /// </summary>
        [HttpPut("{id:int}")]
        public async Task<IActionResult> Update(int id, [FromBody] LabTest input)
        {
            try
            {
                if (id != input.ID)
                {
                    _logger.LogWarning("ID mismatch: URL ID {UrlId} does not match body ID {BodyId}", id, input.ID);
                    return BadRequest(new { message = "ID mismatch" });
                }

                var ok = await _repo.UpdateAsync(input);
                if (!ok)
                {
                    _logger.LogWarning("Lab test with ID {Id} not found for update", id);
                    return NotFound(new { message = $"Lab test with ID {id} not found" });
                }

                _logger.LogInformation("Updated lab test with ID {Id}", id);
                return NoContent();
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error updating lab test {Id} in database", id);
                return StatusCode(500, "An error occurred while updating the lab test");
            }
        }

        /// <summary>
        /// Soft delete a lab test in SQL Server (sets IsDeleted = true)
        /// </summary>
        [HttpDelete("{id:int}")]
        public async Task<IActionResult> Delete(int id)
        {
            try
            {
                var ok = await _repo.SoftDeleteAsync(id);
                if (!ok)
                {
                    _logger.LogWarning("Lab test with ID {Id} not found for deletion", id);
                    return NotFound(new { message = $"Lab test with ID {id} not found" });
                }

                _logger.LogInformation("Soft deleted lab test with ID {Id}", id);
                return NoContent();
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error deleting lab test {Id} from database", id);
                return StatusCode(500, "An error occurred while deleting the lab test");
            }
        }
    }
}


